
groups:
- name: Virtustream-CloudFoundry
  jobs:
  - integration

jobs:
- name: integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true,         get: cf-persist-boshrelease}
  - task: integration
    docker-image: &docker
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: {{docker_repo}}
          insecure_registries: [{{docker_registry}}]
    config:
      <<: *docker
      inputs:
      - name: cf-persist-boshrelease
      params:
        BROKER_PASSWORD: {{broker_password}}
        BROKER_PLANS: {{broker_plans}}
        BROKER_PORT: {{broker_port}}
        BROKER_SERVICE_NAME: {{broker_service_name}}
        BROKER_SERVICE_UUID: {{broker_service_uuid}}
        BROKER_USERNAME: {{broker_username}}
        CF_DOMAIN: {{cf_domain}}
        CF_PASSWORD: {{cf_password}}
        CF_USERNAME: {{cf_username}}
        DIEGO_DRIVER_NAME: {{diego_driver_name}}
        LIBSTORAGE_URI: {{libstorage_uri}}
        STATIC_IP: {{static_ip}}
      run:
        path: cf-persist-boshrelease/ci/tasks/deploy-persist-release

resources:
- name: cf-persist-boshrelease
  type: git
  source:
    uri: https://github.com/EMC-CMD/emc-persistence-release
    branch: master
    skip_ssl_verification: true
